apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: transportations
  namespace: eventstreams
spec:
  partitions: 1
  replicas: 3
  topicName: vaccine.transportation
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824